version: '3.8'

services:
  webhook-server:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    env_file:
      - .env
    volumes:
      - ./src:/app/src:ro
      - ./logs:/app/logs
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - webhook-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - webhook-network

  # Optional: PostgreSQL for storing webhook data
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: webhooks
      POSTGRES_USER: webhook_user
      POSTGRES_PASSWORD: webhook_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - webhook-network

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - webhook-server
    restart: unless-stopped
    networks:
      - webhook-network

volumes:
  redis-data:
  postgres-data:

networks:
  webhook-network:
    driver: bridge